import * as THREE from "three";
import { xrDepthMeshOptions } from "xrblocks";

/**
 * DepthMeshClone is a custom Mesh that acts as a "Shadow Catcher."
 * It is designed to mimic the geometry of the real world (the depth mesh)
 * while remaining invisible, showing only the shadows cast upon it.
 */
export class DepthMeshClone extends THREE.Mesh {
  constructor() {
    // 1. Initialize the parent THREE.Mesh
    super(
      // Start with a simple placeholder geometry (will be replaced later)
      new THREE.PlaneGeometry(),

      // Use ShadowMaterial: This material is invisible (transparent)
      // EXCEPT for areas where a shadow is being cast.
      new THREE.ShadowMaterial({
        // Use the default opacity level defined in XR Blocks settings
        opacity: xrDepthMeshOptions.depthMesh.shadowOpacity,
        // depthWrite: false ensures this invisible mesh doesn't accidentally
        // "cut holes" in other 3D objects behind it.
        depthWrite: false,
      })
    );

    // This object catches shadows from others, but doesn't need to
    // receive shadows from itself.
    this.receiveShadow = false;
  }

  /**
   * Updates this object to perfectly match the physical room geometry
   * captured by the AR device.
   * @param {THREE.Mesh} depthMesh - The real-time mesh generated by the AR sensors.
   */
  cloneDepthMesh(depthMesh) {
    // 1. Clean up old geometry from memory to prevent memory leaks
    this.geometry.dispose();

    // 2. Clone the geometry (the shape) of the real-world depth mesh
    // This makes this mesh "wrap" over your real-world floor, tables, and walls.
    this.geometry = depthMesh.geometry.clone();

    // 3. Sync the Transform (Position, Rotation, and Scale)
    // This ensures the "shadow catcher" stays perfectly aligned with the real world.
    depthMesh.getWorldPosition(this.position);
    depthMesh.getWorldQuaternion(this.quaternion);
    depthMesh.getWorldScale(this.scale);
  }
}
